# Generated by Django 2.0.5 on 2018-06-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180627_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
